services:
  postgres:
    profiles: ["bundled-postgres"]
  traefik:
    profiles: ["bundled-traefik"]
  gateway:
    depends_on: !reset {}

networks:
  traefik:
    external: true
  postgres:
    external: true
